version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependabot"
      - "actions"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/"
    labels:
      - "dependabot"
      - "pub"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
