name: mediary
description: Track drug usage without judgement.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  grouped_list: ^5.1.2
  sticky_headers: ^0.3.0+2
  flutter_riverpod: ^2.4.4
  uuid: ^4.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_localizations:
    sdk: flutter
  calendar_view: ^1.0.4
  settings_ui: ^2.0.2
  flutter_localized_locales: ^2.0.5
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1
  url_launcher: ^6.1.14
  dynamic_color: ^1.6.8
  flutter_file_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint:
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
