name: Build APKs

on:
  push:
    tags: 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_KEY_ALIAS: ${{ vars.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Restore packages
        run: flutter pub get

      - name: Build APKs
        run: flutter build apk --split-per-abi

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/flutter-apk/*.apk.sha1
